apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: apish
    version: v2
  name: apish-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apish
        version: v1
    spec:
      containers:
        - image: krkr/go-apish:latest
          name: apish
          ports:
            - containerPort: 4242
              name: http